### ISSUE TITLE
Importing from GINML adds wrong nodes

### ISSUE THREAD

**Issue by matthiasbock** [matthiasbock/BooleSim#38]
Import from GINML doesn't work properly. Additional nodes with name "FALSE" are added in JavaScript. They do not show up in the network.
Why are they there ?

These nodes are getting exported to Python and R aswell, which breaks the model.

**Comment by chaitan3** [comment]
https://github.com/matthiasbock/BooleSim/issues/28

Refer to the last 2 comments

**Comment by TillS** [comment]
Yes, we know, but we re-opened this issue for a reason. Since we're about to re-submit in a few days, we really need this issue to be sorted out, because although our tool doesn't interpret the wrong falses, they still appear in python and R export and will make trouble if interpreted with other software. If someone for instance wants to extend an existing .ginml model with our software then analyse the extended model with a package like BoolNet, he will encounter trouble! This is a reason for rejection when I look at the previous rejection reasons of the reviewer and we don't want to be rejected again I think. So shouldn't it be possible to erase the remaining falses? It would definitely be great if we could do that and I think this will really be the last remaining main issue to fix now! cheers!

**Comment by chaitan3** [comment]
Ok, agreed. 

The reason I was apprehensive about fixing the issue is because I did not want to tamper with the GINML parsing code. During GSoC I remember that I had spent a lot of time debugging the simulation of GINML files. One small error in the parsing code could alter the entire state space. But as you have pointed out that it may be a point for rejection, the bug should be squashed.

PS: Matthias's latest commit should fix the issue I think.
